name: polymetis-local
channels:
  - conda-forge
  - pytorch
  - fair-robotics
  - aihabitat
dependencies:
  - python=3.8
  - cmake
  - eigen=3.3.9
  - grpc-cpp
  - libprotobuf
  - mkl-include
  - poco
  - urdfdom
  - urdfdom_headers
  - yaml-cpp
  - doxygen
  - pinocchio
  - assimp
  - pybullet
  - mujoco
  - habitat-sim
  - numpy
  - scipy
  - pandas
  - plotly
  - spdlog
  - grpcio
  - protobuf
  - pytest
  - black
  - tqdm
  - pip
  - pip:
      - withbullet
      - pymodbus
      - pyserial
      - sphinx
      - sphinx-copybutton
      - sphinx-book-theme
      - myst-parser
      - dash
      - breathe
      - asv
      - pytest-benchmark
      - hydra-core
      - importlib-resources
